Ticket Cancellation
Gemini-Solutions/helpdesk_automation pull request #12
Opened 2023-03-21 13:35 UTC by gem-aditya-Saraswat

2023-03-21 19:29 UTC, gem-akhil-singh requested changes
* Do follow the mentioned comments 
* Use Pascal Case in classnames , and camelCase in the variable names there are lot of files which are left 
* You test Code should be inside src/test not src/main
* Please dont add all the files from git , add the Code files only , by mistake you might have done git add . . Please remove them from the commit

2023-03-21 19:29 UTC, gem-akhil-singh commented on src/main/java/selectors/Calender_Xpath.java
Change Class Name, follow Pascal Case and Use CamelCase in Selector Variable Names

2023-03-21 19:29 UTC, gem-akhil-singh commented on src/main/java/selectors/Sorting_Xpath.java
Change ClassName Use Pascal Case

2023-03-21 19:29 UTC, gem-akhil-singh commented on src/main/java/stepdefination/Calender_StepDefination.java
> +            calUtils.select_specified_date(endDate);
Here , Gem Test Reporter not used for Reporting , It was needed or not ?

2023-03-21 19:29 UTC, gem-akhil-singh commented on src/main/java/stepdefination/Login_StepDefination.java
> +public class Login_StepDefination extends GemjarTestngBase {
Speliing of Definition and use pascal case in the Class name

2023-03-23 12:32 UTC, gem-aditya-Saraswat commented on src/main/java/stepdefination/Calender_StepDefination.java
> +            calUtils.select_specified_date(endDate);
Done

2023-03-23 12:32 UTC, gem-aditya-Saraswat commented on src/main/java/stepdefination/Calender_StepDefination.java
> +            calUtils.verifyDataForRange(startDate, endDate);
Done

2023-03-23 12:33 UTC, gem-aditya-Saraswat commented on target/classes/features/Ticket_Creation.feature
> +      |  Sample ticket| Sample Description text   | IT          | C:\Users\Aditya.Saraswat\Documents\Upload\sample.doc       |
Done

2023-03-23 12:34 UTC, closed without merging