Hd tushar
Gemini-Solutions/helpdesk_automation pull request #15
Opened 2023-03-22 05:18 UTC by gem-tusharmahajan

2023-03-22 11:04 UTC, gem-rishabhrastogi commented on src/test/java/com/qa/helpdesk/commonutils/Utils.java
> +import helpdesk.stepdefination.StepDefinition;
Use correct spelling for stepdefinition package

2023-03-22 11:35 UTC, gem-rishabhrastogi commented on src/test/java/com/qa/helpdesk/locators/SearchInTickets.java
> +package helpdesk.locators;
-> Refrain from using hard-coded indexing while creating xpaths

2023-03-22 11:36 UTC, gem-rishabhrastogi commented on src/test/java/com/qa/helpdesk/stepdefination/Hook.java
> +package helpdesk.stepdefination;
Please follow proper naming conventions [Start() -> start()]

2023-03-22 12:00 UTC, gem-rishabhrastogi requested changes
Added some suggestions. Please work on those.

2023-03-27 12:09 UTC, gem-rishabhrastogi commented on src/test/java/com/qa/helpdesk/commonutils/Utils.java
> +    GemTestReporter.addTestStep("Verify button is clicked",btnName+ " button is not present and clicked",STATUS.FAIL,DriverAction.takeSnapShot());
Only 'btnName+" is not present" is enough.

2023-04-05 06:36 UTC, Gem-NeerajSingh commented on src/test/java/com/qa/helpdesk/stepdefinition/StepDefinition.java
> +    @And("^Select \"([^\"]*)\" and select \"([^\"]*)\" in filter tab$")
{String}

2023-04-05 06:37 UTC, Gem-NeerajSingh requested changes
changes req

2023-04-05 06:38 UTC, closed without merging