Login and create ticket scenarios
Gemini-Solutions/helpdesk_automation pull request #2
Opened 2023-03-16 11:36 UTC by gem-abhishek-gautam

Added misc files to gitignore. Please review @Gem-NeerajSingh

2023-03-16 15:41 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/locators/Locator.java
> +    public static By login_button = By.xpath("//button[contains(text(),'Login')]");
Use camelcassing instead of _

2023-03-16 15:54 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/StepDefinition.java
> +                DriverAction.click(Locator.login_button);
What if the loginButton does not exist? No error will be thrown.

2023-03-16 16:14 UTC, Gem-NeerajSingh requested changes
minor changes required

2023-03-16 16:21 UTC, gem-abhishek-gautam commented on src/main/java/com/qa/helpdesk/stepDefinitions/StepDefinition.java
> +            String actual_url = DriverAction.getCurrentURL();
Change done

2023-03-16 16:21 UTC, gem-abhishek-gautam commented on src/main/java/com/qa/helpdesk/locators/Locator.java
> +
Change done

2023-03-16 16:22 UTC, gem-abhishek-gautam commented on src/main/java/com/qa/helpdesk/locators/Locator.java
> +    public static By ms_pswd = By.xpath("//input[@type='password']");
identifiers renamed

2023-03-16 16:22 UTC, gem-abhishek-gautam commented on src/main/java/com/qa/helpdesk/locators/Locator.java
> +    public static By login_button = By.xpath("//button[contains(text(),'Login')]");
changes done

2023-03-16 16:23 UTC, gem-abhishek-gautam commented
@Gem-NeerajSingh Requested changes pushed

2023-03-17 09:08 UTC, Gem-NeerajSingh commented on src/main/resources/features/searchAndSort.feature
> +    Examples:
For validation purpose then shoud be used

2023-03-17 09:09 UTC, Gem-NeerajSingh requested changes
Minor changes req

2023-03-17 09:14 UTC, gem-abhishek-gautam commented on src/main/resources/features/searchAndSort.feature
> +    Examples:
Added

2023-03-17 09:21 UTC, gem-abhishek-gautam commented
Requested changes done

2023-03-19 15:00 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/locators/Locator.java
> +
Similar type of xpaths can be used by calling a function with parameter with the string typ

2023-03-19 15:03 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/FilterAndPageStepDefinition.java
> +        List<WebElement> elements = DriverAction.getElements(Locator.getTableRows);
Exception handling req in case locater not found

2023-03-19 15:04 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/FilterAndPageStepDefinition.java
> +                DriverAction.click(Locator.itFilterButton);
use Exception handing or check presence of element before the operation

2023-03-19 15:05 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/FilterAndPageStepDefinition.java
> +
Apply above mention change to entire tc

2023-03-19 15:05 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/FilterAndPageStepDefinition.java
> +
Or throws can be used as well

2023-03-19 15:06 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/FilterAndPageStepDefinition.java
> +}
Apply above mentioned changes to this test case as well

2023-03-19 15:08 UTC, Gem-NeerajSingh commented on src/main/resources/features/CreateTicket.feature
> +    Then submit and verify the incident details for subject "<subject>", dept "<dept>" and description "<desc>"
Submit operation shd be done in given or in when

2023-03-19 15:08 UTC, Gem-NeerajSingh commented on src/main/resources/features/CreateTicket.feature
> +    Then submit and verify the request details for subject "<subject>", dept "<dept>", description "<desc>", category "<catg>" and sub-category "<sub>"
Submit operation shd be done in given or in when

2023-03-19 15:08 UTC, Gem-NeerajSingh commented on src/main/resources/features/CreateTicket.feature
> +    Examples:
Submit operation shd be done in given or in when

2023-03-19 15:09 UTC, Gem-NeerajSingh commented on src/main/resources/features/FilterAndPagination.feature
> +      Then select filter criteria as department "<dept>" and status "<status>"
Then shd only be used for verifictaion cahnge Select filter to When or And

2023-03-19 15:10 UTC, Gem-NeerajSingh commented on src/main/resources/features/SearchAndSort.feature
> +    Then check sorting button for "Status" column
Replace Check with verify

2023-03-19 15:12 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/utils/CommonUtils.java
> +}
Exception handling and Presence of element check missing in entire java file

2023-03-19 15:13 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/SearchAndSortStepDefinition.java
> +        if(DriverAction.isExist(Locator.getAllTableElements)) {
Surround this with try/catch

2023-03-19 15:14 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/TicketStepDefinition.java
> +            CommonUtils.createIncidentTicket(subject,desc,dept,filePath);
path shd be relative put pdf file in resource folder in a seprate package

2023-03-19 15:17 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/TicketStepDefinition.java
> +            CommonUtils.createRequestTicket(subject,desc,dept,category,subCategory,"");
Why sending blank description

2023-03-19 15:21 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/TicketStepDefinition.java
> +            DriverAction.click(Locator.submitForm);
Visibility / presence of element check

2023-03-19 15:21 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/TicketStepDefinition.java
> +            DriverAction.click(Locator.submitForm);
Visibility / presence of element check

2023-03-19 15:23 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/TicketStepDefinition.java
> +            CommonUtils.createRequestTicket(subject,desc,dept,category,subCategory,filePath);
path shd be relative put pdf file in resource folder in a separate package

2023-03-19 15:23 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/TicketStepDefinition.java
> +            DriverAction.click(Locator.submitForm);
Visibility / presence of element check

2023-03-19 15:23 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/TicketStepDefinition.java
> +            DriverAction.waitSec(5);
Visibility / presence of element check

2023-03-19 15:24 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/TicketStepDefinition.java
> +
Visibility / presence of element check apply for above tc

2023-03-19 15:24 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/TicketStepDefinition.java
> +    }
Visibility / presence of element check apply for above tc

2023-03-19 15:24 UTC, Gem-NeerajSingh commented on src/main/java/com/qa/helpdesk/stepDefinitions/TicketStepDefinition.java
> +            DriverAction.click(Locator.submitForm);
Visibility / presence of element check

2023-03-19 15:25 UTC, Gem-NeerajSingh requested changes
Apply mentioned changes for all the occurrence ifany missed in files

2023-03-20 12:08 UTC, gem-abhishek-gautam commented on src/main/java/com/qa/helpdesk/locators/Locator.java
> +
done

2023-03-20 12:08 UTC, gem-abhishek-gautam commented on src/main/java/com/qa/helpdesk/stepDefinitions/FilterAndPageStepDefinition.java
> +        List<WebElement> elements = DriverAction.getElements(Locator.getTableRows);
done

2023-03-20 12:09 UTC, gem-abhishek-gautam commented on src/main/java/com/qa/helpdesk/stepDefinitions/FilterAndPageStepDefinition.java
> +                DriverAction.click(Locator.itFilterButton);
done

2023-03-21 06:54 UTC, closed without merging