Hd aditya Review updates, code refactor and Dashboard, calendar updates
Gemini-Solutions/helpdesk_automation pull request #23
Opened 2023-03-29 11:30 UTC by gem-aditya-Saraswat

2023-03-31 09:52 UTC, gem-akhil-singh requested changes
Please address the mentioned changes in the respective files and code blocks.

2023-03-31 09:52 UTC, gem-akhil-singh commented on src/test/java/selectors/CalenderXpath.java
> +    public static String prevNext = "//div[@class='rdrMonthAndYearWrapper']//button[2]";
Does Indexing is the last thing which could be done here ?  If not , then try creating xpath independent of index

2023-03-31 09:52 UTC, gem-akhil-singh commented on src/test/java/stepdefination/DashboardEmployeeViewStepDefinition.java
> +            List<String> windowList = new ArrayList<>(getWindowHandles());
Dont Use List for storing window handels Use Set for storing window handles. List can have duplicate values Set can't;
Read Here For Detail ; https://stackoverflow.com/questions/36053853/why-we-use-set-in-window-handles-in-selenium-and-not-list

2023-03-31 09:52 UTC, gem-akhil-singh commented on src/test/java/stepdefination/DashboardEmployeeViewStepDefinition.java
> +            String expectedUrl = "https://helpdeskui-np.geminisolutions.com/#/";
These Properties should be fetched from resource files, Create a property or json file in Resources and fetch these values from there

2023-03-31 09:52 UTC, gem-akhil-singh commented on src/test/java/stepdefination/DashboardEmployeeViewStepDefinition.java
> +            String expectedUrl = "https://helpdeskui-np.geminisolutions.com/#/";
expected URL

2023-03-31 09:52 UTC, gem-akhil-singh commented on src/test/java/utilities/CalenderUtils.java
> +                if (inrangeDates.size() == 29 || inrangeDates.size() == 28 || inrangeDates.size() == 26 || inrangeDates.size() == 25){
I have Recommended changes in the Last PR for the Dates its not yet Imeplemented

2023-03-31 09:52 UTC, gem-akhil-singh commented on src/test/java/utilities/CalenderUtils.java
> +            ArrayList<String> dateCreateOn = new ArrayList<>();
What is the Use of this ArrayList here ? its not being called or added or fetched values in the code

2023-03-31 09:52 UTC, gem-akhil-singh commented on src/test/java/utilities/LoginUtils.java
> +            String expURL = "https://helpdeskui-np.geminisolutions.com/#/dashboard/0";
Fetch expURL from Resources folder, create a resource File

2023-03-31 09:52 UTC, gem-akhil-singh commented on src/test/java/utilities/LoginUtils.java
> +            String expURL = "https://helpdeskui-np.geminisolutions.com/#/dashboard/0";
or can also be used from gemjar config file , create a key and use

2023-04-04 05:33 UTC, gem-aditya-Saraswat commented on src/test/java/selectors/CalenderXpath.java
> +    public static String prevNext = "//div[@class='rdrMonthAndYearWrapper']//button[2]";
Yes, I have tried. But indexing is the last approach here.

2023-04-04 05:35 UTC, gem-aditya-Saraswat commented on src/test/java/utilities/CalenderUtils.java
> +            ArrayList<String> dateCreateOn = new ArrayList<>();
I am working in this method it is not yet completed.

2023-04-04 05:36 UTC, gem-aditya-Saraswat commented on src/test/java/utilities/LoginUtils.java
> +            String expURL = "https://helpdeskui-np.geminisolutions.com/#/dashboard/0";
Will look into the right approach for this.

2023-04-04 05:36 UTC, closed without merging