hd-Himanshu (PR)
Gemini-Solutions/helpdesk_automation pull request #30
Opened 2023-04-04 10:10 UTC by Gem-Himanshu-Panchal

Hi @gem-pawandeep, please review my code.

2023-04-04 10:15 UTC, gem-pawandeep commented on src/test/java/com/qa/helpdesk/stepdefinition/HomePage.java
> +            if (DriverAction.isExist(CommonLocators.elementById("input", subject))) {
remove this so many if else use & operator here

2023-04-04 10:17 UTC, gem-pawandeep requested changes
1. remove static waits.
2. remove System.out.println statements.
3. remove so many if else statements use AND condition.

2023-04-04 10:19 UTC, Gem-Himanshu-Panchal commented on src/test/java/com/qa/helpdesk/stepdefinition/HomePage.java
> +            if (DriverAction.isExist(CommonLocators.elementById("input", subject))) {
Okay using && operator in single if condition

2023-04-04 10:20 UTC, gem-pawandeep commented on src/test/java/com/qa/helpdesk/stepdefinition/HomePage.java
> +            if (DriverAction.isExist(CommonLocators.elementById("input", subject))) {
yes

2023-04-04 11:43 UTC, Gem-Himanshu-Panchal commented on src/test/java/com/qa/helpdesk/stepdefinition/HomePage.java
> +            if (DriverAction.isExist(CommonLocators.elementById("input", subject))) {
Working on dynamic waits, rest all the changes are done.

2023-04-04 11:46 UTC, gem-pawandeep approved these changes
looks good!!!

2023-04-05 07:31 UTC, gem-pawandeep requested changes
1. Please remove all the statics waits it impacts code speed.
2. remove dead code.

2023-04-20 07:03 UTC, closed without merging